!obj:pylearn2.cross_validation.TrainCV {
    dataset_iterator:
        !obj:pylearn2.cross_validation.dataset_iterators.StratifiedDatasetKFold {
            dataset: !obj:pylearn2.datasets.dense_design_matrix.DenseDesignMatrix &dataset {
                "X": !pkl: "training_data_100_components_for_pylearn2.pkl",
                "y": !pkl: "training_labels_for_pylearn2.pkl",
                "view_converter": !obj:pylearn2.datasets.dense_design_matrix.DefaultViewConverter {
                    shape: [32, 32, 1],
                    axes: ['b', 0, 1, 'c'],
                },
                "preprocessor": !obj:pylearn2.datasets.preprocessing.Pipeline {
                    items: [
                        !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {
                            subtract_mean: 1,
                            use_std: 1,
                            #sqrt_bias: 10,
                        },
                            #!pkl: "zca_fit_with_unlabeled_training.pkl"
                    ]
                },
            },
            n_folds: 7,
            shuffle: False
        },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: %(batch_size)i,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [32, 32],
            num_channels: 1
        },
        layers: [
            !obj:pylearn2.models.mlp.ConvElemwise {
                 layer_name: 'conv1',
                 output_channels: %(output_channels_conv1)i,
                 pool_type: 'max',
                 kernel_shape: [4, 4],
                 pool_shape: [2, 2],
                 pool_stride: [2, 2],
                 irange: .005,
                 max_kernel_norm: 1.9365,
                 nonlinearity: !obj:pylearn2.models.mlp.TanhConvNonlinearity {}
             }, !obj:pylearn2.models.mlp.ConvElemwise {
                 layer_name: 'conv2',
                 output_channels: %(output_channels_conv2)i,
                 pool_type: 'max',
                 kernel_shape: [4, 4],
                 pool_shape: [2, 2],
                 pool_stride: [2, 2],
                 irange: .005,
                 max_kernel_norm: 1.9365,
                 nonlinearity: !obj:pylearn2.models.mlp.TanhConvNonlinearity {}
             }, !obj:pylearn2.models.mlp.ConvElemwise {
                 layer_name: 'conv3',
                 pool_type: 'max',
                 output_channels: %(output_channels_conv3)i,
                 kernel_shape: [4, 4],
                 pool_shape: [2, 2],
                 pool_stride: [2, 2],
                 irange: .005,
                 max_kernel_norm: 1.9365,
                 nonlinearity: !obj:pylearn2.models.mlp.TanhConvNonlinearity {}
             }, !obj:pylearn2.models.mlp.RectifiedLinear {
                 layer_name: 'h1',
                 dim: %(num_hiddens_h1)i,
                 irange: 0.5,
                 # Rather than using weight decay, we constrain the norms of the weight vectors
                 max_col_norm: 1.
             }, !obj:pylearn2.models.mlp.Softmax {
                 max_col_norm: 1.9365,
                 layer_name: 'y',
                 n_classes: 7,
                 istdev: .05
            }
        ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: %(batch_size)i,
        train_iteration_mode: 'even_shuffled_sequential',
        monitor_iteration_mode: 'even_sequential',
        learning_rate: %(learning_rate)f,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: %(init_momentum)f
        },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: { 
                'conv1' : .8,
                'conv2' : 0.75,
                'conv3' : 0.75,
                'h1' : .5,
                'y' : 1. 
            },
            input_scales: {
                'conv1' : 1.25,
                'conv2' : 1.33,
                'conv3' : 1.33,
                'h1' : 2.,
                'y' : 1.
            },
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 200
                },
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "test_y_misclass",
                    prop_decrease: 0.02,
                    N: 20
                }
            ]
        },
    },
    extensions: [
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 500,
            final_momentum: 0.99
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 868,
            decay_factor: 0.05
        }
    ],
    # We save the model whenever we improve on the validation set classification error
    cv_extensions: [
        !obj:pylearn2.cross_validation.train_cv_extensions.MonitorBasedSaveBestCV {
            channel_name: 'test_y_misclass',
            save_path: "stratified_crossval_best_convnet_models_large_filters.pkl"
        },
    ],
}


